language: node_js
node_js:
  - "9.8.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli
  - npm run test

script:
  -  npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change